repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
          - "--no-ensure-ascii"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        name: "Enforce LF newlines on most files"
        args:
          - "--fix=lf"
        # Exclude files with "crlf" in their names.
        exclude: "crlf|.bat$"
      - id: mixed-line-ending
        name: "Enforce CRLF newlines on files named '*crlf*'"
        args:
          - "--fix=crlf"
        files: "crlf|.bat$"
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-docstring-first
  - repo: local
    hooks:
      - id: cookiecutter
        name: cookiecutter (test-run)
        stages: [pre-push]
        language: system
        entry: ./test_cookies.sh
        pass_filenames: false
        always_run: true
