repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
          - "--no-ensure-ascii"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
  - repo: local
    hooks:
      - id: cookiecutter
        name: cookiecutter (test-run)
        stages: [pre-push]
        language: system
        entry: ./test_cookies.py
        pass_filenames: false
        always_run: true
      - id: cookiecutter-ci
        name: cookiecutter (ci-test-run)
        stages: [manual]
        language: system
        entry: ./test_cookies.py -k public/
        pass_filenames: false
        always_run: true
